# Generated by Django 4.2.5 on 2023-10-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsonmodel',
            old_name='key',
            new_name='city',
        ),
    ]
